### ISSUE TITLE
SASJs Install ERROR on the Linux server

### ISSUE THREAD

**Issue by venkattoluchuri** [sasjs/cli#1161]
I am getting below issue while installing sasjs on linux server

npm i -g @sasjs/cli
⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠹ idealTree:lib: sill idealTree buildDeps
⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠹ idealTree:lib: sill idealTree buildDeps
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/@sasjs%2fcli failed, reason: unable to get local issuer certificate

npm ERR! A complete log of this run can be found in:
npm ERR! /home/hpsas/.npm/_logs/2022-03-14T10_20_53_566Z-debug-0.log

**Comment by allanbowe** [comment]
This appears to be an issue with NPM rather than SASjs.  According to this post: https://stackoverflow.com/questions/36494336/npm-install-error-unable-to-get-local-issuer-certificate

You could try this **quick and insecure** solution:
```bash
npm config set strict-ssl false
```

Or, a better approach if you have the `.pem` file, is to add this entry to `.npmrc`:

```bash
cafile=./ca-certs.pem
```

**Comment by venkattoluchuri** [comment]
Issue resolved. Thank you.
