### ISSUE TITLE
sasjs doc not generating full documentation

### ISSUE THREAD

**Issue by mblauw-sas** [sasjs/cli#1260]
For a client I'm currently creating the documentation using sasjs doc. Unfortunately the lineage part does show all in-/output tables. Files in sub-directories seem to be excluded from the documentation.

**Comment by allanbowe** [comment]
Thanks for raising, @mblauw-sas 

@sabhas - the issue is that the `sasjs doc` command is not considering jobs in subfolders (of the `jobFolders` array) for the generation of the data lineage.

Jobs in subfolders ARE recognised in `sasjs compile` and also in the doxygen `sasjs doc` web pages.

It's just the generation of the GraphViz Data Lineage diagram (driven from the program headers).

To reproduce:

```
sasjs create demo -t jobs
cd demo
sasjs doc
```

If you open the doc site, you CAN see the `jobs/extract/01_setup/setup1.sas` job in the folder tree.

However you do NOT see the `flatfile.policy_dump` table linking to the `src.policy_table` table in the Lineage SVG, which it should be, per the setup1.sas program header.
