### ISSUE TITLE
sasjs job execution failure

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#229]
For some reason when running `sasjs job` I always get `Error creating Folder` 

![https://i.imgur.com/V52O3hS.png](https://i.imgur.com/V52O3hS.png)

**Comment by YuryShkoda** [comment]
for commands that support `targetName` without `--target` flag a warning `WARNING: use --target or -t flag to specify the target name. Specifying the target name without a flag will not be supported starting from November 1, 2021.`

**Comment by krishna-acondy** [comment]
@allanbowe @YuryShkoda I was unable to replicate this issue on my mac, so it could be Windows-specific.
I did, however, notice that the `-l` argument is intended to represent a path to a folder rather than to a file.
The log file is then created as `{jobName}-log.json` in the provided path.
It might be good to try the command with a folder log path just to check if it resolves the issue.

**Comment by allanbowe** [comment]
Tried that, no cigar - perhaps its windows indeed

![](https://i.imgur.com/TIGojnT.png)

**Comment by allanbowe** [comment]
assigning it to Saad following discussion
