### ISSUE TITLE
How to submit a job using sasjs from a GitHub path like as https://github.com/xxx/test.sas

### ISSUE THREAD

**Issue by venkattoluchuri** [sasjs/cli#808]

**Comment by allanbowe** [comment]
The goal of this ticket is to be able to run a program (eg from `sasjs run` ) from a URL instead of the local filesystem.

For instance:

`sasjs run https://raw.githubusercontent.com/sasjs/core/main/base/mf_existfeature.sas`

@venkattoluchuri  - this wouldn't be relevant for `sasjs job execute` as that can only execute _deployed_ jobs (those in SAS Drive or a metadata folder).
